branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.4"
env:
  - FORMAT=true
  - TESTS=float32
  - TESTS=float64
before_install:
  - |
      if [ $TESTS ]; then
        sudo apt-get install -qq libatlas3gf-base libatlas-dev liblapack-dev gfortran
        wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        ./miniconda.sh -b
        export PATH=/home/travis/miniconda/bin:$PATH
        conda update -q --yes conda
      fi
install:
  - |
      if [ $TESTS ]; then
        conda install -q --yes python=$TRAVIS_PYTHON_VERSION nose numpy pip coverage six scipy
        pip install -q --no-deps git+git://github.com/Theano/Theano.git
        pip install -q nose2[coverage-plugin] coveralls
        git clone -q git://github.com/lisa-lab/pylearn2.git
        (cd pylearn2; python setup.py -q develop)
      fi
  - |
      if [ $FORMAT ]; then
        pip install -q flake8
        pip install -q git+git://github.com/bartvm/pep257.git@numpy
      fi
script:
  - if [ $TESTS ]; then THEANO_FLAGS=floatX=$TESTS,blas.ldflags='-lblas -lgfortran' coverage run --source=blocks -m nose2.__main__ tests; fi
  - if [ $FORMAT ]; then flake8 blocks tests; pep257 blocks --numpy --ignore=D100,D101,D102,D103; fi
after_script:
  - if [ $TESTS ]; then coveralls; fi
